# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf7ea6e7f333c7e5fda8d268a50feb9303a6f29418da8f24deb7ecc0d161265559945dcfdaa3c1662092956414c7f99818733221550c379c8e3746cf1803fe3

test:
  secret_key_base: bd880ae168d9f7d74d0a24c42fa3c207949bc938029d1fcd9f01c77d8bfc278fa8afacb8910ef96909e10d05b1cb29d37b27924b3fa9c69903436d4440214999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
